# Generated by Django 3.1.1 on 2020-09-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lib', '0002_auto_20200917_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='founded',
            field=models.DateField(verbose_name='foundation date'),
        ),
    ]
