# Generated by Django 3.1.1 on 2020-09-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lib', '0003_auto_20200917_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='founded',
            field=models.DateTimeField(verbose_name='foundation date'),
        ),
    ]
