# Generated by Django 3.1.1 on 2020-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lib', '0004_auto_20200917_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='founded',
        ),
        migrations.AddField(
            model_name='publisher',
            name='foundation_date',
            field=models.DateField(default='1990-1-1', verbose_name='foundation date'),
        ),
    ]
