# Generated by Django 3.1.1 on 2020-09-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lib', '0006_auto_20200917_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
