# Generated by Django 3.1.1 on 2020-09-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lib', '0007_document_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rating',
            field=models.IntegerField(choices=[(0, ' '), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=0),
        ),
    ]
